import Head from "next/head";
import Banner from "../components/banner/banner";
import Navbar from "../components/nav/navbar";
import styles from "../styles/Home.module.css";
import SectionCards from "../components/card/section-cards";
import { getVideosByQuery, getPopularVideos } from "../lib/videos";

export default function Home({
  disneyVideos,
  travelVideos,
  productivityVideos,
  popularVideos,
}) {
  return (
    <div>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Navbar username="ali@test.com" />
        <Banner
          title="A Hero"
          subTitle="an Asghar Farhadi production"
          imgUrl="/static/a-hero.jpg"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} size="large" />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const [disneyVideos, travelVideos, productivityVideos, popularVideos] =
    await Promise.all([
      getVideosByQuery("disney trailer"),
      getVideosByQuery("travel"),
      getVideosByQuery("productivity"),
      getPopularVideos(),
    ]);

  return {
    props: { disneyVideos, travelVideos, productivityVideos, popularVideos },
  };
}
