import Head from "next/head";
import Banner from "../components/banner/banner";
import Navbar from "../components/nav/navbar";
import styles from "../styles/Home.module.css";
import SectionCards from "../components/card/section-cards";
import {
  getVideosByQuery,
  getPopularVideos,
  getWatchItAgainVideos,
} from "../lib/videos";
import { getUserIdFromToken } from "../lib/utils";

export default function Home({
  disneyVideos,
  travelVideos,
  productivityVideos,
  popularVideos,
  watchItAgainVideos,
}) {
  return (
    <div>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Navbar />
        <Banner
          id="zAJ6_lmr_HQ"
          title="A Hero"
          subTitle="an Asghar Farhadi production"
          imgUrl="/static/a-hero.jpg"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} size="large" />
          <SectionCards
            title="Watch it again"
            videos={watchItAgainVideos}
            size="small"
          />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps({ req }) {
  try {
    const token = req.cookies.token;
    const userId = getUserIdFromToken(token);

    const [
      disneyVideos,
      travelVideos,
      productivityVideos,
      popularVideos,
      watchItAgainVideos,
    ] = await Promise.all([
      getVideosByQuery("disney trailer"),
      getVideosByQuery("travel"),
      getVideosByQuery("productivity"),
      getPopularVideos(),
      getWatchItAgainVideos(userId, token),
    ]);

    return {
      props: {
        disneyVideos,
        travelVideos,
        productivityVideos,
        popularVideos,
        watchItAgainVideos,
      },
    };
  } catch (error) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
}
